//CHARACTERS
export const FETCH_CHARACTERS_START = "FETCH_CHARACTERS_START";
export const SET_FETCHED_CHARACTERS = "SET_FETCHED_CHARACTERS";
//LOCATIONS
export const FETCH_LOCATIONS_START = "FETCH_LOCATIONS_START";
export const SET_FETCHED_LOCATIONS = "SET_FETCHED_LOCATIONS";
//spinner
export const SPINNER_START = "SPINNER_START";
export const SPINNER_STOP = "SPINNER_STOP";
