//data
export const FETCH_DATA_START = "FETCH_DATA_START";
export const SET_FETCHED_DATA = "SET_FETCHED_DATA";
//characters
export const FETCH_CHARACTERS_START = "FETCH_CHARACTERS_START";
export const SET_FETCHED_CHARACTERS = "SET_FETCHED_CHARACTERS";
//spinner
export const SPINNER_START = "SPINNER_START";
export const SPINNER_STOP = "SPINNER_STOP";
